### ISSUE TITLE
[task] update bump ini from 1.3.5 to 1.3.8

### ISSUE THREAD

**Issue by NavruzJn** [AtlantisUnited/serenity#137]
Надо проверить ПР #136 и обновить зависимости

**Comment by TorinAsakura** [comment]
Зачем ты создал задачу на обновление зависимости?Оо

**Comment by NavruzJn** [comment]
> Зачем ты создал задачу на обновление зависимости?Оо

Чтоб трекать чем я занимаюсь ))))
А для такого типа задач не обязательно создать ишью?
